name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  google_maps_flutter: ^2.7.0
  location: ^7.0.0
  flutter_polyline_points: ^2.1.0
  stop_watch_timer: ^3.1.1
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/splash1.json

